apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harness-idp-service-flow-3
  description: harness-idp-service-flow-3 created using self service flow
  annotations:
    harness.io/project-url: "https://app.harness.io/ng/account/qQg-poUqSlqFl9CeAJVmzg/module/cd/orgs/default/projects/TutorialPei/pipelines/Unified_CICD/executions/?storeType=INLINE"
    backstage.io/techdocs-ref: dir:.
    
spec:
  type: service
  owner: test
  lifecycle: experimental
